# Site settings
title: Samuel Granvik | A Personal Portfolio
description: "This website serves as: a portfolio and digital CV, a window into my personal interests, and well-crafted blog posts."
keywords: "portfolio, digital CV, blog, Samuel Granvik"
author: "Samuel Granvik"
url: "https://www.samuelgranvik.tech"
github_username: krullmizter
lang: en

# Theme settings
remote_theme: jekyll/minima
minima:
  skin: dark

# Permalink settings
permalink: /:categories/:title/

# Custom assets
css:
  - assets/css/style.css
js:
  - assets/js/script.js

# Blog posts pagination settings
pagination:
  enabled: true
  items: 5
  per_page: 5
  paginate_path: "/blog/page:num"

# Navigation settings
header_pages:
  - index.html
  - blog/index.html
  - pages/bachelor-thesis.md

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme

# Exclude unnecessary files from the build
exclude:
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE
